-- Criação da Sequence
CREATE TABLE CPGAS_BISTEFANINI (
    CHAVE_PRIMARIA NUMBER(19,0) PRIMARY KEY,
    DESCRICAO VARCHAR2(255 CHAR) NOT NULL,    
    HABILITADO NUMBER(1, 0) DEFAULT 1,
    VERSAO NUMBER(5, 0) DEFAULT 0,
    ULTIMA_ALTERACAO TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
);

-- Comentários para a Tabela
COMMENT ON TABLE CPGAS_BISTEFANINI IS 'Tabela de BIStefanini';

-- Comentários para as Colunas
COMMENT ON COLUMN CPGAS_BISTEFANINI.CHAVE_PRIMARIA IS 'Chave primária da tabela';
COMMENT ON COLUMN CPGAS_BISTEFANINI.DESCRICAO IS 'Descrição do BIStefanini';
COMMENT ON COLUMN CPGAS_BISTEFANINI.HABILITADO IS 'Indicador de que o registro está ativo para o sistema (0-Nao, 1-Sim)';
COMMENT ON COLUMN CPGAS_BISTEFANINI.VERSAO IS 'Número da versão do registro, utilizado para controle de concorrência';
COMMENT ON COLUMN CPGAS_BISTEFANINI.ULTIMA_ALTERACAO IS 'Data e hora da realização da última alteração';

-- Criação da Sequence
CREATE SEQUENCE SQ_CPGAS_BISTEFANINI_CD
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;