UPDATE CONTRATO_PONTO_CONSUMO copc
SET COPC_IN_FATURA_FISICA = 0,
COPC_DS_LOGRADOURO_FATURA = (
  SELECT COALESCE(pocn.POCN_DS_LOGRADOURO, cep.CEP_NM_LOGRADOURO)
  FROM PONTO_CONSUMO pocn
  LEFT JOIN CEP cep ON pocn.CEP_CD = cep.CEP_CD
  WHERE copc.POCN_CD = pocn.POCN_CD
),
COPC_NR_IMOVEL_FATURA = (
  SELECT pocn.POCN_NR_IMOVEL
  FROM PONTO_CONSUMO pocn
  WHERE copc.POCN_CD = pocn.POCN_CD
),
COPC_DS_COMPLEMENTO_FATURA = (
  SELECT pocn.POCN_DS_COMPLEMENTO
  FROM PONTO_CONSUMO pocn
  WHERE copc.POCN_CD = pocn.POCN_CD
),
COPC_DS_BAIRRO_FATURA = (
  SELECT pocn.POCN_DS_BAIRRO
  FROM PONTO_CONSUMO pocn
  WHERE copc.POCN_CD = pocn.POCN_CD
),
COPC_DS_CEP_FATURA = (
  SELECT pocn.POCN_DS_CEP
  FROM PONTO_CONSUMO pocn
  WHERE copc.POCN_CD = pocn.POCN_CD
),
COPC_DS_MUNICIPIO_FATURA = (
  SELECT pocn.POCN_DS_MUNICIPIO
  FROM PONTO_CONSUMO pocn
  WHERE copc.POCN_CD = pocn.POCN_CD
),
COPC_DS_UF_FATURA = (
  SELECT pocn.POCN_DS_UF
  FROM PONTO_CONSUMO pocn
  WHERE copc.POCN_CD = pocn.POCN_CD
);