ALTER TABLE PONTO_CONSUMO
DROP COLUMN POCN_IN_FATURA_FISICA;

ALTER TABLE PONTO_CONSUMO
DROP COLUMN POCN_DS_LOGRADOURO_FATURA;

ALTER TABLE PONTO_CONSUMO
DROP COLUMN POCN_NR_IMOV_FATURA;

ALTER TABLE PONTO_CONSUMO
DROP COLUMN POCN_DS_COMPLEMENTO_FATURA;

ALTER TABLE PONTO_CONSUMO
DROP COLUMN POCN_DS_BAIRRO_FATURA;

ALTER TABLE PONTO_CONSUMO
DROP COLUMN POCN_DS_CEP_FATURA;

ALTER TABLE PONTO_CONSUMO
DROP COLUMN POCN_DS_MUNICIPIO_FATURA;

ALTER TABLE PONTO_CONSUMO
DROP COLUMN POCN_DS_UF_FATURA;