ALTER TABLE USUARIO_SISTEMA ADD USSI_NOME VARCHAR2(150);
ALTER TABLE USUARIO_SISTEMA ADD USSI_EMAIL VARCHAR2(150);

COMMENT ON COLUMN USUARIO_SISTEMA.USSI_NOME IS 'Nome do funcionário.';
COMMENT ON COLUMN USUARIO_SISTEMA.USSI_EMAIL IS 'E-mail do funcionário.';