CREATE TABLE PERMISSAO (
   PERM_CD NUMBER(19,0) PRIMARY KEY, 
	PERM_DS VARCHAR2(255 CHAR) NOT NULL, 
	PERM_NR_VERSAO NUMBER(10,0) DEFAULT 0, 
	PERM_DS_COMPLEMENTO VARCHAR2(255 CHAR), 
	PERM_IN_USO NUMBER(1,0) DEFAULT 1, 
	PERM_TM_ULTIMA_ALTERACAO TIMESTAMP (6));

COMMENT ON COLUMN PERMISSAO.PERM_CD IS 'Chave primária gerada automaticamente e controlada pela sequence SQ_PERM_CD';
COMMENT ON COLUMN PERMISSAO.PERM_DS IS 'Descrição da permissao';
COMMENT ON COLUMN PERMISSAO.PERM_NR_VERSAO IS 'Número da versão do registro, utilizado para controle de concorrência';
COMMENT ON COLUMN PERMISSAO.PERM_DS_COMPLEMENTO IS 'Descrição complementar da permissao';
COMMENT ON COLUMN PERMISSAO.PERM_IN_USO IS 'Indicador de que o registro está ativo para o sistema (0-Nao, 1-Sim)';
COMMENT ON COLUMN PERMISSAO.PERM_TM_ULTIMA_ALTERACAO IS 'Data e hora da realização da última alteração';
  
CREATE SEQUENCE SQ_PERM_CD START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE USUARIO_PERMISSOES(
   USPE_CD NUMBER(19,0) PRIMARY KEY, 
	USSI_CD NUMBER(19, 0) NOT NULL,
   PERM_CD NUMBER(19, 0) NOT NULL,
   USPE_NR_VERSAO NUMBER(10,0) DEFAULT 0, 
	USPE_IN_USO NUMBER(1, 0) DEFAULT 1,
	USPE_TM_ULTIMA_ALTERACAO TIMESTAMP (6));
    
COMMENT ON COLUMN USUARIO_PERMISSOES.USPE_CD IS 'Chave primária gerada automaticamente e controlada pela sequence SQ_USPE_CD';
COMMENT ON COLUMN USUARIO_PERMISSOES.USSI_CD IS 'Chave da tabela Usuario_Sistema';
COMMENT ON COLUMN USUARIO_PERMISSOES.PERM_CD IS 'chave da tabela Permissao';
COMMENT ON COLUMN USUARIO_PERMISSOES.USPE_NR_VERSAO IS 'Número da versão do registro, utilizado para controle de concorrência';
COMMENT ON COLUMN USUARIO_PERMISSOES.USPE_IN_USO IS 'Indicador de que o registro está ativo para o sistema (0-Nao, 1-Sim)';
COMMENT ON COLUMN USUARIO_PERMISSOES.USPE_TM_ULTIMA_ALTERACAO IS 'Data e hora da realização da última alteração';
  
CREATE SEQUENCE SQ_USPE_CD START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE GRUPO (
    GRUP_CD NUMBER(19,0) PRIMARY KEY, 
	GRUP_DS VARCHAR2(255 CHAR) NOT NULL, 
	GRUP_DS_COMPLEMENTO VARCHAR2(255 CHAR), 
	GRUP_NR_VERSAO NUMBER(10,0) DEFAULT 0, 
	GRUP_IN_USO NUMBER(1,0) DEFAULT 1, 
	GRUP_TM_ULTIMA_ALTERACAO TIMESTAMP (6));

COMMENT ON COLUMN GRUPO.GRUP_CD IS 'Chave primária gerada automaticamente e controlada pela sequence SQ_GRUP_CD';
COMMENT ON COLUMN GRUPO.GRUP_DS IS 'Descrição do Grupo';
COMMENT ON COLUMN GRUPO.GRUP_DS_COMPLEMENTO IS 'Descrição complementar do Grupo';
COMMENT ON COLUMN GRUPO.GRUP_NR_VERSAO IS 'Número da versão do registro, utilizado para controle de concorrência';
COMMENT ON COLUMN GRUPO.GRUP_IN_USO IS 'Indicador de que o registro está ativo para o sistema (0-Nao, 1-Sim)';
COMMENT ON COLUMN GRUPO.GRUP_TM_ULTIMA_ALTERACAO IS 'Data e hora da realização da última alteração';
  
CREATE SEQUENCE SQ_GRUP_CD START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE GRUPO_PERMISSOES(
    GRPE_CD NUMBER(19,0) PRIMARY KEY, 
    GRUP_CD NUMBER(19, 0) NOT NULL,
    PERM_CD NUMBER(19, 0) NOT NULL,
    GRPE_NR_VERSAO NUMBER(10,0) DEFAULT 0, 
	GRPE_IN_USO NUMBER(1, 0) DEFAULT 1,
	GRPE_TM_ULTIMA_ALTERACAO TIMESTAMP (6));
    
COMMENT ON COLUMN GRUPO_PERMISSOES.GRPE_CD IS 'Chave primária gerada automaticamente e controlada pela sequence SQ_USPE_CD';
COMMENT ON COLUMN GRUPO_PERMISSOES.GRUP_CD IS 'Chave da tabela Grupo';
COMMENT ON COLUMN GRUPO_PERMISSOES.PERM_CD IS 'Chave da tabela Permissao';
COMMENT ON COLUMN GRUPO_PERMISSOES.GRPE_NR_VERSAO IS 'Número da versão do registro, utilizado para controle de concorrência';
COMMENT ON COLUMN GRUPO_PERMISSOES.GRPE_IN_USO IS 'Indicador de que o registro está ativo para o sistema (0-Nao, 1-Sim)';
COMMENT ON COLUMN GRUPO_PERMISSOES.GRPE_TM_ULTIMA_ALTERACAO IS 'Data e hora da realização da última alteração';
  
CREATE SEQUENCE SQ_GRPE_CD START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE USUARIO_GRUPOS(
    USGR_CD NUMBER(19, 0) PRIMARY KEY,
	USSI_CD NUMBER(19, 0) NOT NULL,
    GRUP_CD NUMBER(19, 0) NOT NULL,
    USGR_NR_VERSAO NUMBER(10,0) DEFAULT 0, 
	USGR_IN_USO NUMBER(1, 0) DEFAULT 1,
	USGR_TM_ULTIMA_ALTERACAO TIMESTAMP (6));
    
COMMENT ON COLUMN USUARIO_GRUPOS.USGR_CD IS 'Chave primária gerada automaticamente e controlada pela sequence SQ_USGR_CD';
COMMENT ON COLUMN USUARIO_GRUPOS.USSI_CD IS 'Chave da tabela Usuário';
COMMENT ON COLUMN USUARIO_GRUPOS.GRUP_CD IS 'Chave da tabela Grupo';
COMMENT ON COLUMN USUARIO_GRUPOS.USGR_NR_VERSAO IS 'Número da versão do registro, utilizado para controle de concorrência';
COMMENT ON COLUMN USUARIO_GRUPOS.USGR_IN_USO IS 'Indicador de que o registro está ativo para o sistema (0-Nao, 1-Sim)';
COMMENT ON COLUMN USUARIO_GRUPOS.USGR_TM_ULTIMA_ALTERACAO IS 'Data e hora da realização da última alteração';
  
CREATE SEQUENCE SQ_USGR_CD START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


CREATE TABLE RECURSO (
    RECU_CD NUMBER(19,0) PRIMARY KEY, 
	RECU_URL VARCHAR2(255 CHAR) NOT NULL, 
	RECU_VERBO_HTTP VARCHAR2(255 CHAR), 
	RECU_CONSIDERAR_VERBO NUMBER(1,0) DEFAULT 0, 
	RECU_NR_VERSAO NUMBER(10,0) DEFAULT 0, 
	RECU_IN_USO NUMBER(1,0) DEFAULT 1, 
	RECU_TM_ULTIMA_ALTERACAO TIMESTAMP (6));

COMMENT ON COLUMN RECURSO.RECU_CD IS 'Chave primária gerada automaticamente e controlada pela sequence SQ_RECU_CD';
COMMENT ON COLUMN RECURSO.RECU_URL IS 'URL do Recurso';
COMMENT ON COLUMN RECURSO.RECU_VERBO_HTTP IS 'Verbo HTTP da chamada';
COMMENT ON COLUMN RECURSO.RECU_CONSIDERAR_VERBO IS 'Indicador se autorização deve considerar o verbo HTTP';
COMMENT ON COLUMN RECURSO.RECU_NR_VERSAO IS 'Número da versão do registro, utilizado para controle de concorrência';
COMMENT ON COLUMN RECURSO.RECU_IN_USO IS 'Indicador de que o registro está ativo para o sistema (0-Nao, 1-Sim)';
COMMENT ON COLUMN RECURSO.RECU_TM_ULTIMA_ALTERACAO IS 'Data e hora da realização da última alteração';
  
CREATE SEQUENCE SQ_RECU_CD START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE RECURSO_PERMISSOES(
    REPE_CD NUMBER(19,0) PRIMARY KEY, 
    RECU_CD NUMBER(19, 0) NOT NULL,
    PERM_CD NUMBER(19, 0) NOT NULL,
    REPE_NR_VERSAO NUMBER(10,0) DEFAULT 0, 
	REPE_IN_USO NUMBER(1, 0) DEFAULT 1,
	REPE_TM_ULTIMA_ALTERACAO TIMESTAMP (6));
    
COMMENT ON COLUMN RECURSO_PERMISSOES.REPE_CD IS 'Chave primária gerada automaticamente e controlada pela sequence SQ_REPE_CD';
COMMENT ON COLUMN RECURSO_PERMISSOES.RECU_CD IS 'Chave da tabela Recurso';
COMMENT ON COLUMN RECURSO_PERMISSOES.PERM_CD IS 'Chave da tabela Permissao';
COMMENT ON COLUMN RECURSO_PERMISSOES.REPE_NR_VERSAO IS 'Número da versão do registro, utilizado para controle de concorrência';
COMMENT ON COLUMN RECURSO_PERMISSOES.REPE_IN_USO IS 'Indicador de que o registro está ativo para o sistema (0-Nao, 1-Sim)';
COMMENT ON COLUMN RECURSO_PERMISSOES.REPE_TM_ULTIMA_ALTERACAO IS 'Data e hora da realização da última alteração';
  
CREATE SEQUENCE SQ_REPE_CD START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;