ALTER TABLE PONTO_CONSUMO
ADD(
	POCN_IN_FATURA_FISICA NUMBER(1, 0) DEFAULT 0,
	POCN_DS_LOGRADOURO_FATURA VARCHAR2(255 CHAR),
	POCN_NR_IMOV_FATURA VARCHAR2(10 CHAR),
	POCN_DS_COMPLEMENTO_FATURA VARCHAR2(100 CHAR),
	POCN_DS_BAIRRO_FATURA VARCHAR2(50 CHAR),
	POCN_DS_CEP_FATURA VARCHAR2(10 CHAR),
	POCN_DS_MUNICIPIO_FATURA VARCHAR2(50 CHAR),
	POCN_DS_UF_FATURA VARCHAR2(2 CHAR)
);

COMMENT ON COLUMN "PONTO_CONSUMO"."POCN_IN_FATURA_FISICA" IS 'Indica a opção por receber fatura física.';	
COMMENT ON COLUMN "PONTO_CONSUMO"."POCN_DS_LOGRADOURO_FATURA" IS 'Logradouro de entrega da fatura do ponto de consumo.';
COMMENT ON COLUMN "PONTO_CONSUMO"."POCN_NR_IMOV_FATURA" IS 'Número do imóvel de entrega da fatura do ponto de consumo.';
COMMENT ON COLUMN "PONTO_CONSUMO"."POCN_DS_COMPLEMENTO_FATURA" IS 'Complemento do Endereço de entrega da fatura do ponto de consumo.';
COMMENT ON COLUMN "PONTO_CONSUMO"."POCN_DS_BAIRRO_FATURA" IS 'Bairro de entrega da fatura do ponto de consumo.';
COMMENT ON COLUMN "PONTO_CONSUMO"."POCN_DS_CEP_FATURA" IS 'CEP de entrega da fatura do ponto de consumo.';
COMMENT ON COLUMN "PONTO_CONSUMO"."POCN_DS_MUNICIPIO_FATURA" IS 'Município de entrega da fatura do ponto de consumo.';
COMMENT ON COLUMN "PONTO_CONSUMO"."POCN_DS_UF_FATURA" IS 'UF de entrega da fatura do ponto de consumo.';
