ALTER TABLE IMOVEL
ADD (
    IMOV_DS_LOGRADOURO VARCHAR2(150 BYTE) NULL,
    IMOV_DS_BAIRRO VARCHAR2(50 BYTE) NULL,
    IMOV_DS_MUNICIPIO VARCHAR2(50 BYTE) NULL,
    IMOV_DS_UF VARCHAR2(2 BYTE) NULL
);
