ALTER TABLE CP_BI_STEFANINI ADD (IN_USO NUMBER(1,0));
ALTER TABLE CP_BI_STEFANINI MODIFY IN_USO DEFAULT 1;
ALTER TABLE CP_BI_STEFANINI ADD (ULTIMA_ALTERACAO TIMESTAMP (6));
ALTER TABLE CP_BI_STEFANINI ADD (NR_VERSAO NUMBER(10,0));
ALTER TABLE CP_BI_STEFANINI MODIFY NR_VERSAO DEFAULT 0;
UPDATE CP_BI_STEFANINI SET IN_USO = 1;
UPDATE CP_BI_STEFANINI SET NR_VERSAO = 0;
UPDATE CP_BI_STEFANINI SET ULTIMA_ALTERACAO = SYSDATE;

ALTER TABLE CPGAS_BI_QUERY ADD (IN_USO NUMBER(1,0));
ALTER TABLE CPGAS_BI_QUERY MODIFY IN_USO DEFAULT 1;
ALTER TABLE CPGAS_BI_QUERY ADD (ULTIMA_ALTERACAO TIMESTAMP (6));
ALTER TABLE CPGAS_BI_QUERY ADD (NR_VERSAO NUMBER(10,0));
ALTER TABLE CPGAS_BI_QUERY MODIFY NR_VERSAO DEFAULT 0;
UPDATE CPGAS_BI_QUERY SET IN_USO = 1;
UPDATE CPGAS_BI_QUERY SET NR_VERSAO = 0;
UPDATE CPGAS_BI_QUERY SET ULTIMA_ALTERACAO = SYSDATE;

ALTER TABLE CP_BI_JASPER ADD (IN_USO NUMBER(1,0));
ALTER TABLE CP_BI_JASPER MODIFY IN_USO DEFAULT 1;
ALTER TABLE CP_BI_JASPER ADD (ULTIMA_ALTERACAO TIMESTAMP (6));
ALTER TABLE CP_BI_JASPER ADD (NR_VERSAO NUMBER(10,0));
ALTER TABLE CP_BI_JASPER MODIFY NR_VERSAO DEFAULT 0;
UPDATE CP_BI_JASPER SET IN_USO = 1;
UPDATE CP_BI_JASPER SET NR_VERSAO = 0;
UPDATE CP_BI_JASPER SET ULTIMA_ALTERACAO = SYSDATE;

ALTER TABLE CP_BI_PARAMENTRO ADD (IN_USO NUMBER(1,0));
ALTER TABLE CP_BI_PARAMENTRO MODIFY IN_USO DEFAULT 1;
ALTER TABLE CP_BI_PARAMENTRO ADD (ULTIMA_ALTERACAO TIMESTAMP (6));
ALTER TABLE CP_BI_PARAMENTRO ADD (NR_VERSAO NUMBER(10,0));
ALTER TABLE CP_BI_PARAMENTRO MODIFY NR_VERSAO DEFAULT 0;
UPDATE CP_BI_PARAMENTRO SET IN_USO = 1;
UPDATE CP_BI_PARAMENTRO SET NR_VERSAO = 0;
UPDATE CP_BI_PARAMENTRO SET ULTIMA_ALTERACAO = SYSDATE;
ALTER TABLE CP_BI_PARAMENTRO
ADD (ENTIDADE_PESQUISA_V2 varchar(50));

UPDATE CP_BI_PARAMENTRO
SET ENTIDADE_PESQUISA_V2 = 
CASE 
    WHEN BIEP_CD IS NULL THEN NULL
    WHEN BIEP_CD = 1 THEN 'PontoConsumo'
    WHEN BIEP_CD = 2 THEN 'Cliente'
    WHEN BIEP_CD = 3 THEN 'Imovel'
    WHEN BIEP_CD = 4 THEN 'Rota'
    WHEN BIEP_CD = 5 THEN 'Segmento'
    WHEN BIEP_CD = 7 THEN 'Periodicidade'
    WHEN BIEP_CD = 8 THEN 'CampanhaDesconto'
END;

ALTER TABLE CP_BI_VALOR_DEFINIDO ADD (IN_USO NUMBER(1,0));
ALTER TABLE CP_BI_VALOR_DEFINIDO MODIFY IN_USO DEFAULT 1;
ALTER TABLE CP_BI_VALOR_DEFINIDO ADD (ULTIMA_ALTERACAO TIMESTAMP (6));
ALTER TABLE CP_BI_VALOR_DEFINIDO ADD (NR_VERSAO NUMBER(10,0));
ALTER TABLE CP_BI_VALOR_DEFINIDO MODIFY NR_VERSAO DEFAULT 0;
UPDATE CP_BI_VALOR_DEFINIDO SET IN_USO = 1;
UPDATE CP_BI_VALOR_DEFINIDO SET NR_VERSAO = 0;
UPDATE CP_BI_VALOR_DEFINIDO SET ULTIMA_ALTERACAO = SYSDATE;