CREATE SEQUENCE SQ_SEGP_CD START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE CPGAS_SEGMENTO_PAI (
    SEGP_CD NUMBER(19,0) PRIMARY KEY, 
	SEGP_DS VARCHAR2(255 CHAR) NOT NULL, 
    SEGP_TIPO_INFO_CADE NUMBER(2,0),
	SEGP_NR_VERSAO NUMBER(10,0) DEFAULT 0,	 
	SEGP_IN_USO NUMBER(1,0) DEFAULT 1, 
	SEGP_TM_ULTIMA_ALTERACAO TIMESTAMP (6)
);

INSERT INTO CPGAS_SEGMENTO_PAI (SEGP_CD, SEGP_DS, SEGP_TIPO_INFO_CADE, SEGP_NR_VERSAO, SEGP_IN_USO, SEGP_TM_ULTIMA_ALTERACAO)
SELECT SQ_SEGP_CD.NEXTVAL, SEGM_DS_FATURA, CASE 
           WHEN SEGM_DS_FATURA = 'RESIDENCIAL' THEN 1 
           ELSE 0 
       END AS tipo, 0, 1, SYSDATE
FROM (SELECT DISTINCT SEGM_DS_FATURA FROM SEGMENTO WHERE SEGM_DS_FATURA IS NOT NULL);