ALTER TABLE SEGMENTO ADD SEGP_CD NUMBER(19,0);

ALTER TABLE SEGMENTO
ADD CONSTRAINT fk_segmento_pai
FOREIGN KEY (SEGP_CD)
REFERENCES CPGAS_SEGMENTO_PAI (SEGP_CD);

UPDATE SEGMENTO segm
SET segm.SEGP_CD = (SELECT segp.SEGP_CD 
            FROM CPGAS_SEGMENTO_PAI segp 
            WHERE segm.SEGM_DS_FATURA = segp.SEGP_DS);