ALTER TABLE CPGAS_CAMPANHA_DESCONTO ADD SEGP_CD NUMBER(19,0);

ALTER TABLE CPGAS_CAMPANHA_DESCONTO
ADD CONSTRAINT fk_cade_segmento_pai
FOREIGN KEY (SEGP_CD)
REFERENCES CPGAS_SEGMENTO_PAI (SEGP_CD);

UPDATE CPGAS_CAMPANHA_DESCONTO cade
SET cade.SEGP_CD = (
    SELECT segp.SEGP_CD
    FROM CPGAS_SEGMENTO_PAI segp
    JOIN ENTIDADE_CONTEUDO enco ON enco.ENCO_DS = segp.SEGP_DS
    WHERE enco.ENCO_CD = cade.ENCO_CD_SEGM_CAMPANHA
);