ALTER TABLE CPGAS_MENU
ADD CONSTRAINT FK_CPGAS_MENU_CPGAS_MENU
FOREIGN KEY (CPME_CD_PAI) REFERENCES CPGAS_MENU(CPME_CD);

-- Início
INSERT INTO CPGAS_MENU (CPME_CD, CPME_DS, CPME_ICON, CPME_URL, CPME_CD_PAI, CPME_NR_ORDEM)
VALUES (SQ_CPME_CD.NEXTVAL, 'Início', 'home', '/', NULL, 0);

-- Cadastros
DECLARE
    v_id NUMBER;
BEGIN
    SELECT SQ_CPME_CD.NEXTVAL INTO v_id FROM dual;
    INSERT INTO CPGAS_MENU (CPME_CD, CPME_DS, CPME_ICON, CPME_URL, CPME_CD_PAI, CPME_NR_ORDEM)
    VALUES (v_id, 'Cadastros', 'edit', NULL, NULL, 1);
    INSERT INTO CPGAS_MENU (CPME_CD, CPME_DS, CPME_ICON, CPME_URL, CPME_CD_PAI, CPME_NR_ORDEM)
    VALUES (SQ_CPME_CD.NEXTVAL, 'Periodicidade', 'calendar-check', '/cadastros/periodicidades/list', v_id, 0);
END;
/

-- Config
DECLARE
    v_id NUMBER;
BEGIN
    SELECT SQ_CPME_CD.NEXTVAL INTO v_id FROM dual;
    INSERT INTO CPGAS_MENU (CPME_CD, CPME_DS, CPME_ICON, CPME_URL, CPME_CD_PAI, CPME_NR_ORDEM)
    VALUES (v_id, 'Config', 'tools', NULL, NULL, 2);
    INSERT INTO CPGAS_MENU (CPME_CD, CPME_DS, CPME_ICON, CPME_URL, CPME_CD_PAI, CPME_NR_ORDEM)
    VALUES (SQ_CPME_CD.NEXTVAL, 'Localização --', 'map-marked-alt', '/', v_id, 0);
    INSERT INTO CPGAS_MENU (CPME_CD, CPME_DS, CPME_ICON, CPME_URL, CPME_CD_PAI, CPME_NR_ORDEM)
    VALUES (SQ_CPME_CD.NEXTVAL, 'Segmento --', 'columns', '/', v_id, 1);
END;
/

-- Comercial
DECLARE
    v_id NUMBER;
BEGIN
    SELECT SQ_CPME_CD.NEXTVAL INTO v_id FROM dual;
    INSERT INTO CPGAS_MENU (CPME_CD, CPME_DS, CPME_ICON, CPME_URL, CPME_CD_PAI, CPME_NR_ORDEM)
    VALUES (v_id, 'Comercial', 'business-time', NULL, NULL, 3);
    INSERT INTO CPGAS_MENU (CPME_CD, CPME_DS, CPME_ICON, CPME_URL, CPME_CD_PAI, CPME_NR_ORDEM)
    VALUES (SQ_CPME_CD.NEXTVAL, 'Cliente', 'user-tie', '/comercial/clientes/list', v_id, 0);
    INSERT INTO CPGAS_MENU (CPME_CD, CPME_DS, CPME_ICON, CPME_URL, CPME_CD_PAI, CPME_NR_ORDEM)
    VALUES (SQ_CPME_CD.NEXTVAL, 'Contrato', 'file-signature', '/comercial/contrato/list', v_id, 1);
    INSERT INTO CPGAS_MENU (CPME_CD, CPME_DS, CPME_ICON, CPME_URL, CPME_CD_PAI, CPME_NR_ORDEM)
    VALUES (SQ_CPME_CD.NEXTVAL, 'Imovel --', 'hotel', '/', v_id, 2);
    INSERT INTO CPGAS_MENU (CPME_CD, CPME_DS, CPME_ICON, CPME_URL, CPME_CD_PAI, CPME_NR_ORDEM)
    VALUES (SQ_CPME_CD.NEXTVAL, 'Ponto de Consumo --', 'map-marker-alt', '', v_id, 3);
END;
/

-- Faturamento
DECLARE
    v_id NUMBER;
BEGIN
    SELECT SQ_CPME_CD.NEXTVAL INTO v_id FROM dual;
    INSERT INTO CPGAS_MENU (CPME_CD, CPME_DS, CPME_ICON, CPME_URL, CPME_CD_PAI, CPME_NR_ORDEM)
    VALUES (v_id, 'Faturamento', 'file-invoice-dollar', NULL, NULL, 4);
    INSERT INTO CPGAS_MENU (CPME_CD, CPME_DS, CPME_ICON, CPME_URL, CPME_CD_PAI, CPME_NR_ORDEM)
    VALUES (SQ_CPME_CD.NEXTVAL, 'Cronograma --', 'list-alt', '/', v_id, 0);
    INSERT INTO CPGAS_MENU (CPME_CD, CPME_DS, CPME_ICON, CPME_URL, CPME_CD_PAI, CPME_NR_ORDEM)
    VALUES (SQ_CPME_CD.NEXTVAL, 'Grupo de Faturamento --', 'object-group', '/', v_id, 1);
END;
/

-- Financeiro
DECLARE
    v_id NUMBER;
BEGIN
    SELECT SQ_CPME_CD.NEXTVAL INTO v_id FROM dual;
    INSERT INTO CPGAS_MENU (CPME_CD, CPME_DS, CPME_ICON, CPME_URL, CPME_CD_PAI, CPME_NR_ORDEM)
    VALUES (v_id, 'Financeiro', 'money-check-alt', NULL, NULL, 5);
    INSERT INTO CPGAS_MENU (CPME_CD, CPME_DS, CPME_ICON, CPME_URL, CPME_CD_PAI, CPME_NR_ORDEM)
    VALUES (SQ_CPME_CD.NEXTVAL, 'Tarifas --', 'percent', '/', v_id, 0);
    INSERT INTO CPGAS_MENU (CPME_CD, CPME_DS, CPME_ICON, CPME_URL, CPME_CD_PAI, CPME_NR_ORDEM)
    VALUES (SQ_CPME_CD.NEXTVAL, 'Tributos', 'hand-holding-usd', '/financeiro/tributos', v_id, 1);
END;
/

-- Manutenção
DECLARE
    v_id NUMBER;
BEGIN
    SELECT SQ_CPME_CD.NEXTVAL INTO v_id FROM dual;
    INSERT INTO CPGAS_MENU (CPME_CD, CPME_DS, CPME_ICON, CPME_URL, CPME_CD_PAI, CPME_NR_ORDEM)
    VALUES (v_id, 'Manutenção', 'wrench', NULL, NULL, 6);
    INSERT INTO CPGAS_MENU (CPME_CD, CPME_DS, CPME_ICON, CPME_URL, CPME_CD_PAI, CPME_NR_ORDEM)
    VALUES (SQ_CPME_CD.NEXTVAL, 'Ceps --', 'address-card', '/', v_id, 0);
END;
/

-- Medição
DECLARE
    v_id NUMBER;
BEGIN
    SELECT SQ_CPME_CD.NEXTVAL INTO v_id FROM dual;
    INSERT INTO CPGAS_MENU (CPME_CD, CPME_DS, CPME_ICON, CPME_URL, CPME_CD_PAI, CPME_NR_ORDEM)
    VALUES (v_id, 'Medição', 'ruler', NULL, NULL, 7);
    INSERT INTO CPGAS_MENU (CPME_CD, CPME_DS, CPME_ICON, CPME_URL, CPME_CD_PAI, CPME_NR_ORDEM)
    VALUES (SQ_CPME_CD.NEXTVAL, 'Medidor', '', '/medicao/medidor/list', v_id, 0);
END;
/

-- Relatórios
DECLARE
    v_id NUMBER;
BEGIN
    SELECT SQ_CPME_CD.NEXTVAL INTO v_id FROM dual;
    INSERT INTO CPGAS_MENU (CPME_CD, CPME_DS, CPME_ICON, CPME_URL, CPME_CD_PAI, CPME_NR_ORDEM)
    VALUES (v_id, 'Relatórios', 'print', NULL, NULL, 8);
    INSERT INTO CPGAS_MENU (CPME_CD, CPME_DS, CPME_ICON, CPME_URL, CPME_CD_PAI, CPME_NR_ORDEM)
    VALUES (SQ_CPME_CD.NEXTVAL, '..', '', '/', v_id, 0);
END;
/