ALTER TABLE CPGAS_CAMPANHA_DESCONTO MODIFY ENCO_CD_SEGM_CAMPANHA NULL;
ALTER TABLE CPGAS_CAMPANHA_DESCONTO MODIFY PORCENTAGEM NULL;
ALTER TABLE CPGAS_CAMPANHA_DESCONTO
ADD (
    VALOR_UNITARIO_POR_VOLUME NUMBER(10, 4),
    QUANTIDADE_VOLUME NUMBER(10, 0)
);

COMMENT ON COLUMN CPGAS_CAMPANHA_DESCONTO.VALOR_UNITARIO_POR_VOLUME IS 'Valor unitário do volume do QDC para o desconto';
COMMENT ON COLUMN CPGAS_CAMPANHA_DESCONTO.QUANTIDADE_VOLUME IS 'Quantidade de volume do QDC para o desconto';
COMMENT ON COLUMN CPGAS_CAMPANHA_DESCONTO.SEGP_CD IS 'Chave estrangeira com a tabela CPGAS_SEGMENTO_PAI';

COMMENT ON COLUMN CPGAS_SEGMENTO_PAI.SEGP_CD IS 'Chave primária gerada automaticamente e controlada pela sequence SQ_SEGP_CD';
COMMENT ON COLUMN CPGAS_SEGMENTO_PAI.SEGP_DS IS 'Descrição do Segmento Pai';
COMMENT ON COLUMN CPGAS_SEGMENTO_PAI.SEGP_TIPO_INFO_CADE IS 'Indicador de qual o tipo de dados a ser escolhido, sendo 0 - Contrato e 1 - Imóvel';
COMMENT ON COLUMN CPGAS_SEGMENTO_PAI.SEGP_NR_VERSAO IS 'Número da versão do registro, utilizado para controle de concorrência';
COMMENT ON COLUMN CPGAS_SEGMENTO_PAI.SEGP_IN_USO IS 'Indicador de que o registro está ativo para o sistema (0-Nao, 1-Sim)';
COMMENT ON COLUMN CPGAS_SEGMENTO_PAI.SEGP_TM_ULTIMA_ALTERACAO IS 'Data e hora da realização da última alteração';

COMMENT ON COLUMN SEGMENTO.SEGP_CD IS 'Chave estrangeira com a tabela CPGAS_SEGMENTO_PAI';